version: 2.1
orbs: 
  slack: circleci/slack@4.10.1
  aws-cli: circleci/aws-cli@3.1
  kubernetes: circleci/kubernetes@1.0.0

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo 'destroy'
  
jobs:
  build-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Application build
          command: |
            cd helloworld
            npm install
      - save_cache:
          paths: [helloworld/node_modules]
          key: helloworld-{{ checksum "helloworld/package.json" }}
      - slack/notify:
          event: fail
          template: basic_fail_1
  
  scan-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - helloworld-{{ checksum "helloworld/package.json" }}
            - helloworld-
          
      - run:
          name: scan-app run
          command: |
            echo {checksum "helloworld/packages.json"}
            cd helloworld
            npm install
            npm audit --audit-level=critical

  create-kubernetes-cluster:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
          
      - run:
          name: Create kubernetes cluster
          command: |
            eksctl create cluster --region=us-east-1 --zones=us-east-1a,us-east-1b
        
  deploy-app:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - setup_remote_docker:
          version: 20.10.14 
      - run:
          name: Linting Dockerfile
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod a+x /bin/hadolint
            sudo hadolint Dockerfile
      - run:
          name: Containerize Application
          command: |
            docker build -t udacitycapstone .
            docker image ls
            
      - run:
          name: Push image
          command: |
            dockerpath="$DOCKER_USER/udacitycapstone:latest"
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag udacitycapstone $dockerpath
            docker push $dockerpath
      - run:
          name: Deploy to Kubernete cluster
          command:  |
            dockerpath="$DOCKER_USER/udacitycapstone:latest"
            aws eks --region us-east-1 update-kubeconfig --name eksctl-capstone
            export KUBECONFIG=/home/circleci/.kube/config
            kubectl create deploy udacity-${CIRCLE_WORKFLOW_ID:0:7} --image=dockerpath
            kubectl expose deployment udacity-${CIRCLE_WORKFLOW_ID:0:7} --type=LoadBalancer --name=publicapp-${CIRCLE_WORKFLOW_ID:0:7} --port=80 --nodeport=3000
            
      - run:
          name: store app endpoint and old
          command: |
            kubectl get services
            api=$(kubectl get services publicapp-${CIRCLE_WORKFLOW_ID:0:7} --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            echo $api >> ~/app-endpoint.txt
            cat  ~/app-endpoint.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - app-endpoint.txt
      - destroy-environment:
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  default:
    jobs:
      - build-app
      - scan-app:
          requires: [build-app]
      - create-kubernetes-cluster:
          requires: [scan-app]
          filters:
            branches:
              only: [main]
      - deploy-app:
          requires: [scan-app, create-kubernetes-cluster]
