version: 2.1
orbs: 
  slack: circleci/slack@4.10.1
  aws-cli: circleci/aws-cli@3.1
  kubernetes: circleci/kubernetes@1.0.0

commands:
  delete-service:
    description: Delete docker image given a workflow ID.
    parameters:
      condition:
        type: string
      workflow_id:
        type: string
    steps:
      - run:
          name: Delete Image
          when: <<parameters.condition>>
          command: |
            kubectl delete service capstoneapp-<<parameters.workflow_id>>
  
jobs:
  build-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Application build
          command: |
            cd helloworld
            npm install
      - save_cache:
          paths: [helloworld/node_modules]
          key: helloworld-{{ checksum "helloworld/package.json" }}
      - slack/notify:
          event: fail
          template: basic_fail_1
  
  scan-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - helloworld-{{ checksum "helloworld/package.json" }}
            - helloworld-
          
      - run:
          name: scan-app run
          command: |
            echo {checksum "helloworld/packages.json"}
            cd helloworld
            npm install
            npm audit --audit-level=critical

  create-kubernetes-cluster:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - run:
          name: Install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
          
      - run:
          name: Create kubernetes cluster
          command: |
            clusterName="capstone-${CIRCLE_WORKFLOW_ID:0:7}"
            eksctl create cluster --name=$clusterName --region=us-east-1 --zones=us-east-1a,us-east-1b
            curl https://kvdb.io/AnCL2AcTbjnej3iwokxmCv/clusterName -d $clusterName
            
  deploy-app:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - setup_remote_docker:
          version: 20.10.14 
      - run:
          name: Linting Dockerfile
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod a+x /bin/hadolint
            sudo hadolint Dockerfile
      - run:
          name: Containerize Application
          command: |
            docker build -t udacitycapstone .
            docker image ls
            
      - run:
          name: Push image
          command: |
            dockerpath="$DOCKER_USER/udacitycapstone:${CIRCLE_WORKFLOW_ID:0:7}"
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag udacitycapstone $dockerpath
            docker push $dockerpath
            
      - run:
          name: Deploy to Kubernete cluster
          command:  |
            export clusterName=$(curl --insecure https://kvdb.io/AnCL2AcTbjnej3iwokxmCv/clusterName)
            dockerpath="$DOCKER_USER/udacitycapstone:${CIRCLE_WORKFLOW_ID:0:7}"
            aws eks --region us-east-1 update-kubeconfig --name ${clusterName}
            export KUBECONFIG=/home/circleci/.kube/config
            kubectl create deploy udacity-${CIRCLE_WORKFLOW_ID:0:7} --image=$dockerpath
            kubectl expose deployment udacity-${CIRCLE_WORKFLOW_ID:0:7} --type=LoadBalancer --name=capstoneapp-${CIRCLE_WORKFLOW_ID:0:7} --port=80 --target-port=3000
            kubectl wait --for=condition=Ready --all pod
            
      - run:
          name: Store app endpoint
          command: |
            api=""
            while [ -z $api ]; do
              api=$(kubectl get services capstoneapp-${CIRCLE_WORKFLOW_ID:0:7} --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
              [ -z "$api" ] && sleep 15
            done
            echo 'Found external hostname: '$api
            echo $api >> ~/app-endpoint.txt
            sleep 1m
      - persist_to_workspace:
          root: ~/
          paths:
            - app-endpoint.txt
  
  smoke-test:
    docker:
       - image: cimg/base:2021.04
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - attach_workspace:
          at: ~/
      - run:
          name: Smoke test.
          command: |
            export APP_ENDPOINT=$(cat ~/app-endpoint.txt)
            echo ${APP_ENDPOINT}
            if curl ${APP_ENDPOINT} | grep "Hello World"
            then
              curl https://kvdb.io/AnCL2AcTbjnej3iwokxmCv/workflowid -d ${CIRCLE_WORKFLOW_ID:0:7}
              exit 0
            else
              exit 1
            fi
            
      - delete-service:
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
          condition: on_fail
  
  cleanup:
    docker:
       - image: cimg/base:2021.04
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - delete-service:
          workflow_id: $(curl --insecure https://kvdb.io/AnCL2AcTbjnej3iwokxmCv/clusterName)
          condition: always
workflows:
  default:
    jobs:
      - build-app
      - scan-app:
          requires: [build-app]
      - create-kubernetes-cluster:
          requires: [scan-app]
          filters:
            branches:
              only: [main]
      - deploy-app:
          requires: [scan-app, create-kubernetes-cluster]
      - smoke-test:
          requires: [deploy-app]
      - cleanup:
          requires: [smoke-test]
